// Generated by CoffeeScript 1.12.7
(function() {
  var FakePromise, sinon;

  sinon = require("sinon");

  FakePromise = require("./FakePromise")["default"];

  describe("FakePromise", function() {
    var testedPromise;
    testedPromise = null;
    beforeEach(function() {
      testedPromise = new FakePromise;
      return void 0;
    });
    describe("just after creation", function() {
      it("throws when calling .resolve(...)", function() {
        return should(function() {
          return testedPromise.resolve(null);
        })["throw"](new Error("promise not specified"));
      });
      return it("throws when calling .reject(...)", function() {
        return should(function() {
          return testedPromise.reject(null);
        })["throw"](new Error("promise not specified"));
      });
    });
    describe("when after .then(onfulfilled) specified", function() {
      var nextPromise, thenCallback;
      thenCallback = null;
      nextPromise = null;
      beforeEach(function() {
        thenCallback = sinon.spy();
        nextPromise = testedPromise.then(thenCallback);
        return void 0;
      });
      it("throws calling .then(...) second time", function() {
        return should(function() {
          return testedPromise.then(thenCallback);
        })["throw"](new Error("promise already specified"));
      });
      it("throws calling .catch(...) on the same promise", function() {
        return should(function() {
          return testedPromise["catch"](thenCallback);
        })["throw"](new Error("promise already specified"));
      });
      describe("and after calling .resolve(arg)", function() {
        var arg;
        arg = "I will behave";
        beforeEach(function() {
          testedPromise.resolve(arg);
          return void 0;
        });
        it("calls proper callback", function() {
          return thenCallback.should.have.callCount(1);
        });
        return it("passes result to callback", function() {
          return thenCallback.should.have.been.calledWith(arg);
        });
      });
      return describe("and after .catch(onrejected) specified on returned promise", function() {
        var catchCallback;
        catchCallback = null;
        beforeEach(function() {
          catchCallback = sinon.spy();
          nextPromise["catch"](catchCallback);
          return void 0;
        });
        return describe("and after calling .reject(err).reject()", function() {
          var err;
          err = new Error("I will never promise again");
          beforeEach(function() {
            testedPromise.reject(err).reject();
            return void 0;
          });
          it("calls proper callback", function() {
            return catchCallback.should.have.callCount(1);
          });
          return it("passes error to callback", function() {
            return catchCallback.should.have.been.calledWith(err);
          });
        });
      });
    });
    describe("when after .then(onfulfilled, onrejected) specified", function() {
      var catchCallback, thenCallback;
      thenCallback = null;
      catchCallback = null;
      beforeEach(function() {
        thenCallback = sinon.spy();
        catchCallback = sinon.spy();
        testedPromise.then(thenCallback, catchCallback);
        return void 0;
      });
      describe("and after calling .resolve(arg)", function() {
        var arg;
        arg = "I will clean my room";
        beforeEach(function() {
          testedPromise.resolve(arg);
          return void 0;
        });
        it("calls proper callback", function() {
          return thenCallback.should.have.callCount(1);
        });
        return it("passes result to callback", function() {
          return thenCallback.should.have.been.calledWith(arg);
        });
      });
      return describe("and after calling .reject(err)", function() {
        var err;
        err = new Error("I will fulfill all promises");
        beforeEach(function() {
          testedPromise.reject(err);
          return void 0;
        });
        it("calls proper callback", function() {
          return catchCallback.should.have.callCount(1);
        });
        return it("passes error to callback", function() {
          return catchCallback.should.have.been.calledWith(err);
        });
      });
    });
    describe("when after .then(passThrough).then(onfulfilled) specified", function() {
      var thenCallback;
      thenCallback = null;
      beforeEach(function() {
        thenCallback = sinon.spy();
        testedPromise.then(function(arg) {
          return arg;
        }).then(thenCallback);
        return void 0;
      });
      return describe("and after calling .resolve(arg).resolve()", function() {
        var arg;
        arg = "I will behave";
        beforeEach(function() {
          testedPromise.resolve(arg).resolve();
          return void 0;
        });
        it("calls proper callback", function() {
          return thenCallback.should.have.callCount(1);
        });
        return it("passes result to callback", function() {
          return thenCallback.should.have.been.calledWith(arg);
        });
      });
    });
    return describe("when after .catch(rethrow).catch(onrejected) specified", function() {
      var catchCallback;
      catchCallback = null;
      beforeEach(function() {
        catchCallback = sinon.spy();
        testedPromise["catch"](function(err) {
          throw err;
        })["catch"](catchCallback);
        return void 0;
      });
      return describe("and after calling .reject(arg).reject()", function() {
        var err;
        err = "I will not promise anything connected with promises";
        beforeEach(function() {
          testedPromise.reject(err).reject();
          return void 0;
        });
        it("calls proper callback", function() {
          return catchCallback.should.have.callCount(1);
        });
        return it("passes error to callback", function() {
          return catchCallback.should.have.been.calledWith(err);
        });
      });
    });
  });

}).call(this);

//# sourceMappingURL=FakePromise.spec.js.map
