// Generated by CoffeeScript 1.12.7
(function() {
  var FakePromise, FunctionProxyHandler, LoggingProxyHandler, sinon;

  sinon = require("sinon");

  FakePromise = require("./FakePromise")["default"];

  describe("FakePromise", function() {
    var testedPromise;
    testedPromise = null;
    beforeEach(function() {
      testedPromise = new FakePromise;
      testedPromise = new Proxy(testedPromise, new LoggingProxyHandler);
      return void 0;
    });
    describe("when after calling .resolve(null)", function() {
      var nextPromise;
      nextPromise = null;
      beforeEach(function() {
        nextPromise = testedPromise.resolve(null);
        return void 0;
      });
      it("calling .then(callback) calls the callback immediately", function() {
        var callback;
        callback = sinon.spy();
        testedPromise.then(callback);
        return callback.should.have.callCount(1).and.have.been.calledWith(null);
      });
      it("calling .catch(callback) does nothing", function() {
        var callback;
        callback = sinon.spy();
        testedPromise["catch"](callback);
        return callback.should.have.callCount(0);
      });
      return describe("and after calling .resolve(null).resolve()", function() {
        beforeEach(function() {
          nextPromise.resolve();
          return void 0;
        });
        return it("calling .then(passThrough).then(callback) calls the callback immediately", function() {
          var callback;
          callback = sinon.spy();
          testedPromise.then(function(arg) {
            return arg;
          }).then(callback);
          return callback.should.have.callCount(1).and.have.been.calledWith(null);
        });
      });
    });
    describe("when after .resolve() without result", function() {
      var nextPromise;
      nextPromise = null;
      beforeEach(function() {
        nextPromise = testedPromise.resolve();
        return void 0;
      });
      return describe("and after calling .setResult(result)", function() {
        var result;
        result = "result";
        beforeEach(function() {
          return testedPromise.setResult(result);
        });
        it("calling .then(callback) calls the callback immediately", function() {
          var callback;
          callback = sinon.spy();
          testedPromise.then(callback);
          return callback.should.have.callCount(1).and.have.been.calledWith(result);
        });
        return it("calling .catch(callback) does nothing", function() {
          var callback;
          callback = sinon.spy();
          testedPromise["catch"](callback);
          return callback.should.have.callCount(0);
        });
      });
    });
    describe("when after .resolve() with resolved promise as result", function() {
      var nextPromise, result;
      nextPromise = null;
      result = "result";
      beforeEach(function() {
        var resultPromise;
        resultPromise = new FakePromise;
        resultPromise.resolve(result);
        nextPromise = testedPromise.resolve(resultPromise);
        return void 0;
      });
      it("calling .then(callback) calls the callback immediately", function() {
        var callback;
        callback = sinon.spy();
        testedPromise.then(callback);
        return callback.should.have.callCount(1).and.have.been.calledWith(result);
      });
      return it("calling .catch(callback) does nothing", function() {
        var callback;
        callback = sinon.spy();
        testedPromise["catch"](callback);
        return callback.should.have.callCount(0);
      });
    });
    describe("when after .resolve() with rejected promise as result", function() {
      var error, nextPromise;
      nextPromise = null;
      error = new Error("rejected");
      beforeEach(function() {
        var resultPromise;
        resultPromise = new FakePromise;
        resultPromise.reject(error);
        nextPromise = testedPromise.resolve(resultPromise);
        return void 0;
      });
      it("calling .catch(callback) calls the callback immediately", function() {
        var callback;
        callback = sinon.spy();
        testedPromise["catch"](callback);
        return callback.should.have.callCount(1).and.have.been.calledWith(error);
      });
      return it("calling .then(callback) does nothing", function() {
        var callback;
        callback = sinon.spy();
        testedPromise.then(callback);
        return callback.should.have.callCount(0);
      });
    });
    describe("when after calling .reject(error)", function() {
      var error, nextPromise;
      error = new Error("test");
      nextPromise = null;
      beforeEach(function() {
        nextPromise = testedPromise.reject(error);
        return void 0;
      });
      it("calling .catch(callback) calls the callback immediately", function() {
        var callback;
        callback = sinon.spy();
        testedPromise["catch"](callback);
        return callback.should.have.callCount(1).and.have.been.calledWith(error);
      });
      it("calling .then(callback) does nothing", function() {
        var callback;
        callback = sinon.spy();
        testedPromise.then(callback);
        return callback.should.have.callCount(0);
      });
      return describe("and after calling .reject(error).reject()", function() {
        beforeEach(function() {
          nextPromise.reject();
          return void 0;
        });
        return it("calling .catch(rethrow).catch(callback) calls the callback immediately", function() {
          var callback;
          callback = sinon.spy();
          testedPromise["catch"](function(me) {
            throw me;
          })["catch"](callback);
          return callback.should.have.callCount(1).and.have.been.calledWith(error);
        });
      });
    });
    describe("when after .then(onfulfilled) specified", function() {
      var nextPromise, thenCallback;
      thenCallback = null;
      nextPromise = null;
      beforeEach(function() {
        thenCallback = sinon.spy();
        nextPromise = testedPromise.then(thenCallback);
        return void 0;
      });
      it("throws calling .then(...) second time", function() {
        return should(function() {
          return testedPromise.then(thenCallback);
        })["throw"](new Error("promise already specified"));
      });
      it("throws calling .catch(...) on the same promise", function() {
        return should(function() {
          return testedPromise["catch"](thenCallback);
        })["throw"](new Error("promise already specified"));
      });
      it(".setResult(undefined).resolve() doesn't throw", function() {
        testedPromise.setResult(void 0);
        testedPromise.resolve();
        return void 0;
      });
      describe("and after calling .resolve(arg)", function() {
        var arg;
        arg = "I will behave";
        beforeEach(function() {
          testedPromise.resolve(arg);
          return void 0;
        });
        it("calls proper callback", function() {
          return thenCallback.should.have.callCount(1);
        });
        return it("passes result to callback", function() {
          return thenCallback.should.have.been.calledWith(arg);
        });
      });
      return describe("and after .catch(onrejected) specified on returned promise", function() {
        var catchCallback;
        catchCallback = null;
        beforeEach(function() {
          catchCallback = sinon.spy();
          nextPromise["catch"](catchCallback);
          return void 0;
        });
        return describe("and after calling .reject(err).reject()", function() {
          var err;
          err = new Error("I will never promise again");
          beforeEach(function() {
            testedPromise.reject(err).reject();
            return void 0;
          });
          it("calls proper callback", function() {
            return catchCallback.should.have.callCount(1);
          });
          return it("passes error to callback", function() {
            return catchCallback.should.have.been.calledWith(err);
          });
        });
      });
    });
    describe("when after .then(onfulfilled, onrejected) specified", function() {
      var catchCallback, thenCallback;
      thenCallback = null;
      catchCallback = null;
      beforeEach(function() {
        thenCallback = sinon.spy();
        catchCallback = sinon.spy();
        testedPromise.then(thenCallback, catchCallback);
        return void 0;
      });
      describe("and after calling .resolve(arg)", function() {
        var arg;
        arg = "I will clean my room";
        beforeEach(function() {
          testedPromise.resolve(arg);
          return void 0;
        });
        it("calls proper callback", function() {
          return thenCallback.should.have.callCount(1);
        });
        return it("passes result to callback", function() {
          return thenCallback.should.have.been.calledWith(arg);
        });
      });
      return describe("and after calling .reject(err)", function() {
        var err;
        err = new Error("I will fulfill all promises");
        beforeEach(function() {
          testedPromise.reject(err);
          return void 0;
        });
        it("calls proper callback", function() {
          return catchCallback.should.have.callCount(1);
        });
        return it("passes error to callback", function() {
          return catchCallback.should.have.been.calledWith(err);
        });
      });
    });
    describe("when after .then(passThrough).then(onfulfilled) specified", function() {
      var thenCallback;
      thenCallback = null;
      beforeEach(function() {
        thenCallback = sinon.spy();
        testedPromise.then(function(arg) {
          return arg;
        }).then(thenCallback);
        return void 0;
      });
      return describe("and after calling .resolve(arg).resolve()", function() {
        var arg;
        arg = "I will behave";
        beforeEach(function() {
          testedPromise.resolve(arg).resolve();
          return void 0;
        });
        it("calls proper callback", function() {
          return thenCallback.should.have.callCount(1);
        });
        return it("passes result to callback", function() {
          return thenCallback.should.have.been.calledWith(arg);
        });
      });
    });
    describe("when after .then(returnResolvedPromise).then(onfulfilled) specified", function() {
      var thenCallback;
      thenCallback = null;
      beforeEach(function() {
        var resultPromise;
        thenCallback = sinon.spy();
        resultPromise = new FakePromise;
        testedPromise.then(function(arg) {
          resultPromise.resolve(arg);
          return resultPromise;
        }).then(thenCallback);
        return void 0;
      });
      return describe("and after calling .resolve(arg).resolve()", function() {
        var arg;
        arg = "I will behave";
        beforeEach(function() {
          testedPromise.resolve(arg).resolve();
          return void 0;
        });
        it("calls proper callback", function() {
          return thenCallback.should.have.callCount(1);
        });
        return it("passes result to callback", function() {
          return thenCallback.should.have.been.calledWith(arg);
        });
      });
    });
    describe("when after .then(returnRejectedPromise).catch(onfulfilled) specified", function() {
      var catchCallback;
      catchCallback = null;
      beforeEach(function() {
        var resultPromise;
        catchCallback = sinon.spy();
        resultPromise = new FakePromise;
        testedPromise.then(function(arg) {
          resultPromise.reject(arg);
          return resultPromise;
        })["catch"](catchCallback);
        return void 0;
      });
      return describe("and after calling .resolve(arg).resolve()", function() {
        var arg;
        arg = "I will behave";
        beforeEach(function() {
          testedPromise.resolve(arg).resolve().reject();
          return void 0;
        });
        it("calls proper callback", function() {
          return catchCallback.should.have.callCount(1);
        });
        return it("passes result to callback", function() {
          return catchCallback.should.have.been.calledWith(arg);
        });
      });
    });
    describe("when after .catch(rethrow).catch(onrejected) specified", function() {
      var catchCallback;
      catchCallback = null;
      beforeEach(function() {
        catchCallback = sinon.spy();
        testedPromise["catch"](function(err) {
          throw err;
        })["catch"](catchCallback);
        return void 0;
      });
      return describe("and after calling .reject(arg).reject()", function() {
        var err;
        err = new Error("This promise is a fake one");
        beforeEach(function() {
          testedPromise.reject(err).reject();
          return void 0;
        });
        it("calls proper callback", function() {
          return catchCallback.should.have.callCount(1);
        });
        return it("passes error to callback", function() {
          return catchCallback.should.have.been.calledWith(err);
        });
      });
    });
    describe("when after .catch(returnRejectedPromise).catch(onrejected) specified", function() {
      var catchCallback;
      catchCallback = null;
      beforeEach(function() {
        var resultPromise;
        catchCallback = sinon.spy();
        resultPromise = new FakePromise;
        testedPromise["catch"](function(err) {
          resultPromise.reject(err);
          return resultPromise;
        })["catch"](catchCallback);
        return void 0;
      });
      return describe("and after calling .reject(arg).reject()", function() {
        var err;
        err = new Error("This promise is a fake one");
        beforeEach(function() {
          testedPromise.reject(err).reject();
          return void 0;
        });
        it("calls proper callback", function() {
          return catchCallback.should.have.callCount(1);
        });
        return it("passes error to callback", function() {
          return catchCallback.should.have.been.calledWith(err);
        });
      });
    });
    describe("when after .catch(returnResolvedPromise).then(onrejected) specified", function() {
      var thenCallback;
      thenCallback = null;
      beforeEach(function() {
        var resultPromise;
        thenCallback = sinon.spy();
        resultPromise = new FakePromise;
        testedPromise["catch"](function(err) {
          resultPromise.resolve(err.message);
          return resultPromise;
        }).then(thenCallback);
        return void 0;
      });
      return describe("and after calling .reject(arg).resolve()", function() {
        var err;
        err = "This promise is a fake one";
        beforeEach(function() {
          testedPromise.reject(new Error(err)).resolve();
          return void 0;
        });
        it("calls proper callback", function() {
          return thenCallback.should.have.callCount(1);
        });
        return it("passes error to callback", function() {
          return thenCallback.should.have.been.calledWith(err);
        });
      });
    });
    describe("when after .setResult(...) called", function() {
      var expectedResult;
      expectedResult = {};
      beforeEach(function() {
        return testedPromise.setResult(expectedResult);
      });
      it("calling .setResult(...) again throws an error", function() {
        return should(function() {
          return testedPromise.setResult(expectedResult);
        })["throw"]("result already set");
      });
      it("calling .resolve(result) throws an error", function() {
        return should(function() {
          return testedPromise.resolve(expectedResult);
        })["throw"]("result already set");
      });
      it("calling .setError(...) throws an error", function() {
        return should(function() {
          return testedPromise.setError(new Error('test'));
        })["throw"]("trying to set error on a promise with result already set");
      });
      it("calling .reject() throws an error", function() {
        return should(function() {
          return testedPromise.reject();
        })["throw"]("trying to reject a promise containing result");
      });
      return it("calling .resolve() does not throw", function() {
        testedPromise.resolve().resolve();
        return testedPromise.then(function(result) {
          return result.should.eql(expectedResult);
        });
      });
    });
    return describe("when after .setError(...) called", function() {
      var expectedError;
      expectedError = new Error("test");
      beforeEach(function() {
        return testedPromise.setError(expectedError);
      });
      it("calling .setError(...) again throws an error", function() {
        return should(function() {
          return testedPromise.setError(expectedError);
        })["throw"]("error already set");
      });
      it("calling .reject(error) throws an error", function() {
        return should(function() {
          return testedPromise.reject(expectedError);
        })["throw"]("error already set");
      });
      it("calling .setError(...) throws an error", function() {
        return should(function() {
          return testedPromise.setResult({});
        })["throw"]("trying to set result on a promise with error already set");
      });
      it("calling .resolve() throws an error", function() {
        return should(function() {
          return testedPromise.resolve();
        })["throw"]("trying to resolve a promise containing error");
      });
      return it("calling .reject() does not throw", function() {
        testedPromise.reject().resolve();
        return testedPromise.then(function() {
          throw new Error("expected rejection");
        }, function(error) {
          return error.should.eql(expectedError);
        });
      });
    });
  });

  FunctionProxyHandler = (function() {
    function FunctionProxyHandler(name) {
      this.name = name;
    }

    FunctionProxyHandler.prototype.apply = function(target, thisArg, argumentList) {
      console.log("call " + this.name + "(" + (argumentList.join(", ")) + ")");
      return target.apply(thisArg, argumentList);
    };

    return FunctionProxyHandler;

  })();

  LoggingProxyHandler = (function() {
    function LoggingProxyHandler() {}

    LoggingProxyHandler.prototype.get = function(target, property, receiver) {
      var value;
      value = target[property];
      console.log("get " + property + " === " + value);
      if (typeof value === "function") {
        return new Proxy(value, new FunctionProxyHandler(property));
      } else {
        return value;
      }
    };

    LoggingProxyHandler.prototype.set = function(target, property, value, receiver) {
      var previous;
      previous = target[property];
      console.log("set " + property + " = " + value + "; previous === " + previous);
      target[property] = value;
      return true;
    };

    return LoggingProxyHandler;

  })();

}).call(this);

//# sourceMappingURL=FakePromise.spec.js.map
